### ISSUE TITLE
Tell her - I'll always be sorry for my chaotic calamity; I've been relentlessly stupidest, and Unauthentic. I fear for apology even today. But nothing more! 

### ISSUE THREAD

**Issue by ghost** [Riddhick/Speaker-Identification-in-Bengali-Language-using-Deep-Neural-Network#1]
## READ aloud 

[If you see her, say hello
She might be in Tangier
She left here last early spring
Is livin' there, I hear..        
// 
Say for me that I'm all right
Though things get kind of slow
She might think that I've forgotten her
Don't tell her it isn't so.     
// 
Oh, whatever makes her happy
I won't stand in the way
Though the bitter taste still lingers on
From the night I tried to make her stay. 
//
](https://www.youtube.com/watch?v=-L3Y7X5eek0)

Anyways - **good project** by the way, you could've used transformer architecture for less spatious semantic embedding, and then you would be able to run the whole model on Raspberry Pi 2B even - or even on edge devices, if you train it with tensorflow lite.

Regards
Vecchio Amico

**Comment by Riddhick** [comment]
Thank you for the suggestions, actually it is a great idea to implement this on a Raspberry Pi and I was thinking to do the same . Also there will be some changes in the project in future, as for now I am waiting for a publication before moving further with this :).
